const pfaList = [
  {id:1, code: '', pfa: 'Access Pensions Limited'},
  {id:2, code: '', pfa: 'ARM Pension Managers Limited'},
  {id:3, code: '', pfa: 'Crusader Sterling Pensions Limited'},
  {id:4, code: '', pfa: 'FCMB Pensions Limited'},
  {id:5, code: '', pfa: 'Fidelity Pension Managers Limited'},
  {id:6, code: '', pfa: 'Guaranty Trust Pension Managers Limited'},
  {id:7, code: '', pfa: 'Leadway Pensure PFA Limited'},
  {id:8, code: '', pfa: 'Nigerian University Pension Management Company (NUPEMCO)'},
  {id:9, code: '', pfa: 'NLPC Pension Fund Administrators Limited'},
  {id:10, code: '', pfa: 'Norrenberger Pensions Limited'},
  {id:11, code: '', pfa: 'NPF Pensions Fund Administrators Limited'},
  {id:12, code: '', pfa: 'OAK Pensions Limited'},
  {id:13, code: '', pfa: 'Pensions Alliance Limited'},
  {id:14, code: '', pfa: 'Premium Pension Limited'},
  {id:15, code: '', pfa: 'Radix Pension Managers Limited'},
  {id:16, code: '', pfa: 'Stanbic IBTC Pension Managers Limited'},
  {id:17, code: '', pfa: 'Tangerine APT Pensions Limited'},
  {id:18, code: '', pfa: 'Trustfund Pensions Limited'},
  {id:19, code: '', pfa: 'Veritas Glanvills Pensions Limited'},
]
